### ISSUE TITLE
posts/2024/vs-code-obsolescence.md

### ISSUE THREAD

**Issue by nurked** [riastrad/cyberbspace#133]
Men, try Zed editor. If you exclude pesky node.js and run Zed without any node-related linters you'll get 300 meg memory footprint. It is written in Rust and I've been using it on my Mac for the past month. I don't have VSCode installed at all. 

Plus, if you are a vim entusiast - it supports vim shorcuts, but it is totally VS-Code compatible.

**Comment by nurked** [comment]
And guess what? 

[macOS](https://zed.dev/docs/system-requirements#macos)

Supported versions: Catalina (10.15) - Sonoma (14.x).

    The implementation of our screen sharing feature makes use of [LiveKit](https://livekit.io/). The LiveKit SDK requires macOS Catalina (10.15); consequently, in v0.62.4, we dropped support for earlier macOS versions that we were initially supporting.

Your OS should be supported.

**Comment by riastrad** [comment]
Appreciate the recommendation! 👍 

I use these issues to track planned changes/improvements to my personal site, so I'm going to close this one out.
